import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#38BDF8",
          accent: "#0EA5E9",
          dark: "#0284C7",
          light: "#F0F9FF",
          border: "#BAE6FD",
          orange: "#F97316",
        },
        danger: "#CA3E1E",
        surface: {
          DEFAULT: "#FFFFFF",
          subtle: "#F9FAFB",
          page: "#F4F6F8",
          mint: "#EAEDE8",
        },
        neutrals: {
          white: "#FFFFFF",
          pageBackground: "#F4F6F8",
          pageBackgroundMint: "#EAEDE8",
          surfaceSubtle: "#F9FAFB",
          border: "#E5E7EB",
          borderLight: "#F0F1F3",
          divider: "#EBEBEB",
        },
        text: {
          primary: "#111827",
          secondary: "#6B7280",
          tertiary: "#9CA3AF",
          onDark: "#FFFFFF",
          onAccent: "#FFFFFF",
          link: "#0284C7",
          danger: "#CA3E1E",
          muted: "#D1D5DB",
        },
        status: {
          successBackground: "#D1FAE5",
          successText: "#065F46",
          successBorder: "#6EE7B7",
          warningBackground: "#FEF3C7",
          warningText: "#92400E",
          warningBorder: "#FCD34D",
          errorBackground: "#FEE2E2",
          errorText: "#991B1B",
          errorBorder: "#FCA5A5",
          infoBackground: "#DBEAFE",
          infoText: "#1E40AF",
          infoBorder: "#93C5FD",
          pendingBackground: "#FEF9C3",
          pendingText: "#854D0E",
          pendingBorder: "#FDE68A",
        },
        roleAccents: {
          student: "#1D4ED8",
          studentBackground: "#DBEAFE",
          alumnus: "#7C3AED",
          alumnusBackground: "#EDE9FE",
          exco: "#065F46",
          excoBackground: "#D1FAE5",
          superAdmin: "#CA3E1E",
          superAdminBackground: "#FEE2E2",
        },
        noteCards: {
          green: "#BBFCCC",
          greenSurface: "#9EF9B3",
          greenText: "#064E3B",
          greenSubtext: "#065F46",
          greenMeta: "#059669",
          purple: "#C4B5FD",
          purpleSurface: "#A78BFA",
          purpleText: "#3B0764",
          purpleSubtext: "#4C1D95",
          purpleMeta: "#6D28D9",
          amber: "#FDE68A",
          amberText: "#78350F",
          amberSubtext: "#92400E",
          blue: "#BFDBFE",
          blueText: "#1E3A8A",
        },
        taskStatus: {
          inProgressBackground: "#FDE68A",
          inProgressText: "#78350F",
          todoBackground: "#DBEAFE",
          todoText: "#1E40AF",
          doneBackground: "#D1FAE5",
          doneText: "#065F46",
          overdueBackground: "#FEE2E2",
          overdueText: "#991B1B",
        },
      },
      fontFamily: {
        sans: ["Inter", "DM Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        card: "12px",
        modal: "16px",
        badge: "9999px",
        session: "6px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.07), 0 1px 2px rgba(0,0,0,0.04)",
        "card-hover": "0 4px 12px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.06)",
        modal: "0 20px 60px rgba(0,0,0,0.15), 0 4px 16px rgba(0,0,0,0.08)",
        dropdown: "0 4px 16px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.06)",
        "input-focus": "0 0 0 3px rgba(56,189,248,0.25)",
        "input-error": "0 0 0 3px rgba(202,62,30,0.12)",
        "pill-tab-active": "0 1px 3px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
export default config;

