import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom palette color names registered directly as Tailwind colors
        "indigo-velvet": "var(--indigo-velvet)",
        "brick-ember": "var(--brick-ember)",
        "alabaster-grey": "var(--alabaster-grey)",
        "amber-honey": "var(--amber-honey)",
        "prussian-blue": "var(--prussian-blue)",
        "prussian-blue-2": "var(--prussian-blue-2)",
        "jade-green": "var(--jade-green)",

        brand: {
          DEFAULT: "var(--brand-default)",
          accent: "var(--brand-accent)",
          dark: "var(--brand-dark)",
          light: "var(--brand-light)",
          border: "var(--brand-border)",
          orange: "var(--brand-orange)",
        },
        danger: "var(--danger)",
        surface: {
          DEFAULT: "var(--surface-default)",
          subtle: "var(--surface-subtle)",
          page: "var(--surface-page)",
          mint: "var(--surface-mint)",
        },
        neutrals: {
          white: "var(--neutrals-white)",
          pageBackground: "var(--neutrals-page-bg)",
          pageBackgroundMint: "var(--neutrals-page-bg-mint)",
          surfaceSubtle: "var(--neutrals-surface-subtle)",
          border: "var(--neutrals-border)",
          borderLight: "var(--neutrals-border-light)",
          divider: "var(--neutrals-divider)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          onDark: "var(--text-on-dark)",
          onAccent: "var(--text-on-accent)",
          link: "var(--text-link)",
          danger: "var(--text-danger)",
          muted: "var(--text-muted)",
        },
        status: {
          successBackground: "var(--success-bg)",
          successText: "var(--success-text)",
          successBorder: "var(--success-border)",
          warningBackground: "var(--warning-bg)",
          warningText: "var(--warning-text)",
          warningBorder: "var(--warning-border)",
          errorBackground: "var(--error-bg)",
          errorText: "var(--error-text)",
          errorBorder: "var(--error-border)",
          infoBackground: "var(--info-bg)",
          infoText: "var(--info-text)",
          infoBorder: "var(--info-border)",
          pendingBackground: "var(--pending-bg)",
          pendingText: "var(--pending-text)",
          pendingBorder: "var(--pending-border)",
        },
        roleAccents: {
          student: "var(--role-student)",
          studentBackground: "var(--role-student-bg)",
          alumnus: "var(--role-alumnus)",
          alumnusBackground: "var(--role-alumnus-bg)",
          exco: "var(--role-exco)",
          excoBackground: "var(--role-exco-bg)",
          superAdmin: "var(--role-superadmin)",
          superAdminBackground: "var(--role-superadmin-bg)",
        },
        noteCards: {
          green: "var(--note-green)",
          greenSurface: "var(--note-green-surface)",
          greenText: "var(--note-green-text)",
          greenSubtext: "var(--note-green-subtext)",
          greenMeta: "var(--note-green-meta)",
          purple: "var(--note-purple)",
          purpleSurface: "var(--note-purple-surface)",
          purpleText: "var(--note-purple-text)",
          purpleSubtext: "var(--note-purple-subtext)",
          purpleMeta: "var(--note-purple-meta)",
          amber: "var(--note-amber)",
          amberText: "var(--note-amber-text)",
          amberSubtext: "var(--note-amber-subtext)",
          blue: "var(--note-blue)",
          blueText: "var(--note-blue-text)",
        },
        taskStatus: {
          inProgressBackground: "var(--task-inprogress-bg)",
          inProgressText: "var(--task-inprogress-text)",
          todoBackground: "var(--task-todo-bg)",
          todoText: "var(--task-todo-text)",
          doneBackground: "var(--task-done-bg)",
          doneText: "var(--task-done-text)",
          overdueBackground: "var(--task-overdue-bg)",
          overdueText: "var(--task-overdue-text)",
        },
      },
      fontFamily: {
        sans: ["Inter", "DM Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        card: "12px",
        modal: "16px",
        badge: "9999px",
        session: "6px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.07), 0 1px 2px rgba(0,0,0,0.04)",
        "card-hover": "0 4px 12px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.06)",
        modal: "0 20px 60px rgba(0,0,0,0.15), 0 4px 16px rgba(0,0,0,0.08)",
        dropdown: "0 4px 16px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.06)",
        "input-focus": "0 0 0 3px rgba(56,189,248,0.25)",
        "input-error": "0 0 0 3px rgba(202,62,30,0.12)",
        "pill-tab-active": "0 1px 3px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
export default config;

